### ISSUE TITLE
I want to fix `デバック` to `デバッグ`

### ISSUE THREAD

**Issue by kishida** [Blue-Puddle-Inc/CODE-COFFEE#10]
on below.
```
エンジニアたちが、このコーヒーはこの言語っぽくない。と喧々諤々と話し合いながら、デバック（試飲）していきました
```
But there is no code that we can fix with PR.

**Comment by shu223** [comment]
Thanks, we fixed it on the official website. Unfortunately, we can't change the Makuake page.
